spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/users_db
    username: user
    password: pass
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always
      
logging:
  level:
    sql: debug
    '[org.hibernate.orm.jdbc.bind]': trace