x-common-config: &common-config
  restart: unless-stopped
  networks: 
    - ecomm-net

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: ecomm-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-user@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-pass}
    ports:
      - 5431:80
    <<: *common-config
    
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: ecomm-rabbitmq
    ports:
      - 15672:15672 # management UI
      - 5672:5672
    <<: *common-config