x-common-env: &common-env
  SPRING_RABBITMQ_HOST: ecomm-rabbitmq
  SPRING_RABBITMQ_PORT: 5672
  SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-guest}
  SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
  MANAGEMENT_OTLP_TRACING_ENDPOINT: http://ecomm-tempo:4317

x-config-disable: &config-disable
  SPRING_CLOUD_BUS_ENABLED: false
  SPRING_CLOUD_CONFIG_ENABLED: false
  SPRING_CLOUD_CONFIG_RETRY_MAXATTEMPTS: 1

x-eureka: &eureka
  EUREKA_SERVER: http://ecomm-service-registry:8082/eureka/

x-redis: &redis
  SPRING_DATA_REDIS_HOST: ecomm-redis
  SPRING_DATA_REDIS_PORT: 6379

x-jwt: &jwt
  SECRET_KEY: ${SECRET_KEY:-gEn3r8EdK3y} # Generate key in Account Management TokenServiceTest class

x-common-config: &common-config
  restart: unless-stopped
  networks: 
    - ecomm-net
  labels:
    logging: "promtail"

services:
  api-gateway:
    build: ../services/ecomm-api-gateway
    container_name: ecomm-api-gateway
    ports:
      - "18080:18080"
      - "8080:8080"
    environment:
      <<: [*common-env, *config-disable, *eureka, *redis, *jwt]
      MANAGEMENT_SERVER_PORT: 18080
      SERVER_PORT: 8080
    depends_on:
      - service-registry
    <<: *common-config

  config-server:
    build: ../services/ecomm-config-server
    container_name: ecomm-config-server
    ports: 
      - "8081:8081"
    environment:
      <<: [*common-env, *eureka]
      SERVER_PORT: 8081
      SPRING_CLOUD_BUS_ENABLED: false
      SPRING_CLOUD_CONFIG_SERVER_ENABLED: false
    <<: *common-config

  service-registry:
    build: ../services/ecomm-service-registry
    container_name: ecomm-service-registry
    ports: 
      - "8082:8082"
    environment:
      <<: [*common-env, *config-disable]
      SERVER_PORT: 8082
    depends_on:
      - config-server
    <<: *common-config

  account-management:
    build: ../services/ecomm-account-management
    container_name: ecomm-account-management
    ports: 
      - "8083:8083"
    environment:
      <<: [*common-env, *config-disable, *eureka, *jwt]
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://account-postgres:5432/users_db
    depends_on:
      - api-gateway
      - account-postgres
    <<: *common-config

  product-catalog:
    build: ../services/ecomm-product-catalog
    container_name: ecomm-product-catalog
    ports: 
      - "8084:8084"
    environment:
      <<: [*common-env, *config-disable, *eureka, *redis]
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-postgres:5432/products_db
    depends_on:
      - api-gateway
      - product-postgres
    <<: *common-config
    
  shopping-cart:
    build: ../services/ecomm-shopping-cart
    container_name: ecomm-shopping-cart
    ports: 
      - "8085:8085"
    environment:
      <<: [*common-env, *config-disable, *eureka, *redis]
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-postgres:5432/carts_db
    depends_on:
      - api-gateway
      - cart-postgres
    <<: *common-config