spring:
  application:
    name: ecomm-service-registry
  config:
    import: 'optional:configserver:'

server.port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8082/eureka/

management:
  endpoints.web:
    exposure.include: '*'