services:
  cart-postgres:
    image: postgres
    container_name: cart-postgres
    environment:
      POSTGRES_DB: carts_db
      POSTGRES_USER: ${CART_PG_USER:-user}
      POSTGRES_PASSWORD: ${CART_PG_PASSWORD:-pass}
    ports:
      - 5434:5432
    restart: unless-stopped
    networks:
      - ecomm-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5