services:
  account-postgres:
    image: postgres
    container_name: account-postgres
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: ${ACCOUNT_PG_USER:-user}
      POSTGRES_PASSWORD: ${ACCOUNT_PG_PASSWORD:-pass}
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - ecomm-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5