services:
  account-postgres:
    image: postgres
    container_name: account-postgres
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: ${ACCOUNT_PG_USER:-user}
      POSTGRES_PASSWORD: ${ACCOUNT_PG_PASSWORD:-pass}
    ports:
      - 5432:5432
    networks:
      - ecomm-net
    restart: unless-stopped