name: Build and Push Account Management Microservice

on:
  pull_request:
    paths:
      - 'services/ecomm-account-management/**'
    branches: 
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install -DskipTests
      working-directory: services/ecomm-account-management

    - name: Build & Push to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/ecomm-account-management
        tags: latest
        registry: docker.io
        dockerfile: services/ecomm-account-management/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
