name: Build and Test Account Management Microservice

env:
  MS_NAME: ecomm-api-gateway

on:
  push:
    paths:
      - 'services/${{ env.MS_NAME }}/**'
    branches-ignore: 
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean test
      working-directory: services/${{ env.MS_NAME }}
