name: Build and Test Account Management Microservice

on:
  push:
    paths:
      - 'services/ecomm-account-management/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: All the Tests and Coverage check
      run: mvn clean install
      working-directory: services/ecomm-account-management
